export interface Product {
  id: string;
  image: string;
  name: string;
  description: string;
  amount: number;
  buyer: string;
  location: string;
  date: string;
  checked: boolean;
}

export const NewProductData: Product[] = [
  {
    id: "123456789",
    image: "/images/yellowPepper.png",
    name: "Coco Yam",
    description: "Freshly harvested coco yam",
    amount: 1200.5,
    buyer: "Emeka Chika",
    location: "Lagos",
    date: "23/09/2025",
    checked: false,
  },
  {
    id: "234567890",
    image: "/images/yellowPepper.png",
    name: "Tomato",
    description: "Ripe red tomatoes",
    amount: 850.75,
    buyer: "Aisha Bello",
    location: "Abuja",
    date: "20/09/2025",
    checked: false,
  },
  {
    id: "345678901",
    image: "/images/yellowPepper.png",
    name: "Okra",
    description: "Fresh green okra",
    amount: 600.0,
    buyer: "Chidi Okonkwo",
    location: "Enugu",
    date: "21/09/2025",
    checked: false,
  },
  {
    id: "456789012",
    image: "/images/yellowPepper.png",
    name: "Yam",
    description: "Large white yams",
    amount: 2000.0,
    buyer: "Fatima Musa",
    location: "Kano",
    date: "22/09/2025",
    checked: false,
  },
  {
    id: "567890123",
    image: "/images/yellowPepper.png",
    name: "Plantain",
    description: "Ripe plantains",
    amount: 950.25,
    buyer: "Tunde Adeyemi",
    location: "Ibadan",
    date: "19/09/2025",
    checked: false,
  },
  {
    id: "678901234",
    image: "/images/yellowPepper.png",
    name: "Pepper",
    description: "Spicy red peppers",
    amount: 400.5,
    buyer: "Ngozi Eze",
    location: "Port Harcourt",
    date: "18/09/2025",
    checked: false,
  },
  {
    id: "789012345",
    image: "/images/yellowPepper.png",
    name: "Egusi",
    description: "Fresh egusi seeds",
    amount: 1500.0,
    buyer: "Sola Adebayo",
    location: "Lagos",
    date: "17/09/2025",
    checked: false,
  },
  {
    id: "890123456",
    image: "/images/yellowPepper.png",
    name: "Vegetable",
    description: "Mixed green vegetables",
    amount: 700.0,
    buyer: "Amaka Obi",
    location: "Abuja",
    date: "16/09/2025",
    checked: false,
  },
];

export const ParkedProductData: Product[] = [
  {
    id: "901234567",
    image: "/images/yellowPepper.png",
    name: "Potato",
    description: "Fresh Irish potatoes",
    amount: 1100.0,
    buyer: "Ifeanyi Nwosu",
    location: "Lagos",
    date: "15/09/2025",
    checked: false,
  },
  {
    id: "012345678",
    image: "/images/yellowPepper.png",
    name: "Cucumber",
    description: "Crisp cucumbers",
    amount: 500.0,
    buyer: "Zainab Ibrahim",
    location: "Kano",
    date: "14/09/2025",
    checked: false,
  },
  {
    id: "123456780",
    image: "/images/yellowPepper.png",
    name: "Carrot",
    description: "Fresh carrots",
    amount: 650.0,
    buyer: "Chukwuma Obi",
    location: "Enugu",
    date: "13/09/2025",
    checked: false,
  },
  {
    id: "234567891",
    image: "/images/yellowPepper.png",
    name: "Onion",
    description: "Red onions",
    amount: 800.0,
    buyer: "Maryam Yusuf",
    location: "Abuja",
    date: "12/09/2025",
    checked: false,
  },
  {
    id: "345678902",
    image: "/images/yellowPepper.png",
    name: "Garlic",
    description: "Fresh garlic bulbs",
    amount: 300.0,
    buyer: "Kemi Ade",
    location: "Ibadan",
    date: "11/09/2025",
    checked: false,
  },
  {
    id: "456789013",
    image: "/images/yellowPepper.png",
    name: "Spinach",
    description: "Green spinach leaves",
    amount: 450.0,
    buyer: "Chinedu Okeke",
    location: "Port Harcourt",
    date: "10/09/2025",
    checked: false,
  },
  {
    id: "567890124",
    image: "/images/yellowPepper.png",
    name: "Beans",
    description: "Brown beans",
    amount: 1300.0,
    buyer: "Bola Ahmed",
    location: "Lagos",
    date: "09/09/2025",
    checked: false,
  },
  {
    id: "678901235",
    image: "/images/yellowPepper.png",
    name: "Lettuce",
    description: "Fresh lettuce",
    amount: 550.0,
    buyer: "Adaeze Nnamdi",
    location: "Abuja",
    date: "08/09/2025",
    checked: false,
  },
];

export const DeliveredProductData: Product[] = [
  {
    id: "789012346",
    image: "/images/yellowPepper.png",
    name: "Maize",
    description: "Yellow maize grains",
    amount: 1400.0,
    buyer: "Oluwaseun Ade",
    location: "Lagos",
    date: "07/09/2025",
    checked: false,
  },
  {
    id: "890123457",
    image: "/images/yellowPepper.png",
    name: "Rice",
    description: "Long grain rice",
    amount: 2000.0,
    buyer: "Hassan Ali",
    location: "Kano",
    date: "06/09/2025",
    checked: false,
  },
  {
    id: "901234568",
    image: "/images/yellowPepper.png",
    name: "Cassava",
    description: "Fresh cassava tubers",
    amount: 900.0,
    buyer: "Chiamaka Eze",
    location: "Enugu",
    date: "05/09/2025",
    checked: false,
  },
  {
    id: "012345679",
    image: "/images/yellowPepper.png",
    name: "Groundnut",
    description: "Roasted groundnuts",
    amount: 1200.0,
    buyer: "Funmi Ola",
    location: "Ibadan",
    date: "04/09/2025",
    checked: false,
  },
  {
    id: "123456781",
    image: "/images/yellowPepper.png",
    name: "Millet",
    description: "Pearl millet grains",
    amount: 1100.0,
    buyer: "Ibrahim Musa",
    location: "Abuja",
    date: "03/09/2025",
    checked: false,
  },
  {
    id: "234567892",
    image: "/images/yellowPepper.png",
    name: "Sorghum",
    description: "Red sorghum grains",
    amount: 1000.0,
    buyer: "Ngozi Okonkwo",
    location: "Port Harcourt",
    date: "02/09/2025",
    checked: false,
  },
  {
    id: "345678903",
    image: "/images/yellowPepper.png",
    name: "Palm Oil",
    description: "Pure palm oil",
    amount: 2500.0,
    buyer: "Tunde Balogun",
    location: "Lagos",
    date: "01/09/2025",
    checked: false,
  },
  {
    id: "456789014",
    image: "/images/yellowPepper.png",
    name: "Ginger",
    description: "Fresh ginger roots",
    amount: 600.0,
    buyer: "Amaka Nwosu",
    location: "Abuja",
    date: "31/08/2025",
    checked: false,
  },
];
