
// Define interfaces for type safety
export interface User {
  id: string;
  userID: string;
  image: string;
  fullname: string;
  location: string;
  profession: string;
  mobile: string;
  email: string;
  status: string;
  date: string;
  checked: boolean;
}

// Sample data with unique IDs and varied user information
export const initialUsers: User[] = [
  {
    id: "AGT001",
    userID: "AGT001",
    image: "/images/TopAgent.png",
    fullname: "John Doe",
    location: "Abia",
    profession: "Agents",
    mobile: "09044885322",
    email: "john.doe@example.com",
    status: "Active",
    date: "02/23/2025",
    checked: false,
  },
  {
    id: "TRN001",
    userID: "TRN001",
    image: "/images/TopAgent.png",
    fullname: "Aisha Bello",
    location: "Lagos - Kano",
    profession: "Transporter",
    mobile: "08123456789",
    email: "aisha.bello@example.com",
    status: "Active",
    date: "03/15/2025",
    checked: false,
  },
  {
    id: "FRM001",
    userID: "FRM001",
    image: "/images/TopAgent.png",
    fullname: "Chukwuma Okeke",
    location: "Port Harcourt",
    profession: "Farmer",
    mobile: "07098765432",
    email: "chukwuma.okeke@example.com",
    status: "Suspended",
    date: "04/01/2025",
    checked: false,
  },
  {
    id: "AGT002",
    userID: "AGT002",
    image: "/images/TopAgent.png",
    fullname: "Fatima Adebayo",
    location: "Enugu",
    profession: "Agents",
    mobile: "09122334455",
    email: "fatima.adebayo@example.com",
    status: "Suspended",
    date: "05/10/2025",
    checked: false,
  },
  {
    id: "TRN002",
    userID: "TRN002",
    image: "/images/TopAgent.png",
    fullname: "Emeka Nwosu",
    location: "Kaduna - Onitsha",
    profession: "Transporter",
    mobile: "08055667788",
    email: "emeka.nwosu@example.com",
    status: "Active",
    date: "06/20/2025",
    checked: false,
  },
  {
    id: "FRM002",
    userID: "FRM002",
    image: "/images/TopAgent.png",
    fullname: "Grace Okafor",
    location: "Ibadan",
    profession: "Farmer",
    mobile: "09011223344",
    email: "grace.okafor@example.com",
    status: "Active",
    date: "07/05/2025",
    checked: false,
  },
  {
    id: "AGT003",
    userID: "AGT003",
    image: "/images/TopAgent.png",
    fullname: "Ibrahim Musa",
    location: "Abuja",
    profession: "Agents",
    mobile: "08199887766",
    email: "ibrahim.musa@example.com",
    status: "Suspended",
    date: "08/12/2025",
    checked: false,
  },
  {
    id: "TRN003",
    userID: "TRN003",
    image: "/images/TopAgent.png",
    fullname: "Ngozi Eze",
    location: "Onitsha - Enugu",
    profession: "Transporter",
    mobile: "07033445566",
    email: "ngozi.eze@example.com",
    status: "Suspended",
    date: "09/18/2025",
    checked: false,
  },
  {
    id: "FRM003",
    userID: "FRM003",
    image: "/images/TopAgent.png",
    fullname: "Yusuf Adamu",
    location: "Kano",
    profession: "Farmer",
    mobile: "09066778899",
    email: "yusuf.adamu@example.com",
    status: "Active",
    date: "10/22/2025",
    checked: false,
  },
  {
    id: "AGT004",
    userID: "AGT004",
    image: "/images/TopAgent.png",
    fullname: "Chioma Udeh",
    location: "Lagos",
    profession: "Agents",
    mobile: "08144556677",
    email: "chioma.udeh@example.com",
    status: "Active",
    date: "11/30/2025",
    checked: false,
  },
  {
    id: "TRN004",
    userID: "TRN004",
    image: "/images/TopAgent.png",
    fullname: "David Ojo",
    location: "Abuja - Jos",
    profession: "Transporter",
    mobile: "07022334455",
    email: "david.ojo@example.com",
    status: "Suspended",
    date: "12/10/2025",
    checked: false,
  },
  {
    id: "FRM004",
    userID: "FRM004",
    image: "/images/TopAgent.png",
    fullname: "Esther Adeyemi",
    location: "Owerri",
    profession: "Farmer",
    mobile: "09111223344",
    email: "esther.adeyemi@example.com",
    status: "Suspended",
    date: "01/15/2026",
    checked: false,
  },
  {
    id: "BYR001",
    userID: "BYR001",
    image: "/images/TopAgent.png",
    fullname: "Amaka Igwe",
    location: "Benin City",
    profession: "Buyer",
    mobile: "08077665544",
    email: "amaka.igwe@example.com",
    status: "Active",
    date: "09/01/2025",
    checked: false,
  },
  {
    id: "BYR002",
    userID: "BYR002",
    image: "/images/TopAgent.png",
    fullname: "Samuel Okonkwo",
    location: "Aba",
    profession: "Buyer",
    mobile: "09133445566",
    email: "samuel.okonkwo@example.com",
    status: "Suspended",
    date: "10/05/2025",
    checked: false,
  },
  {
    id: "BYR003",
    userID: "BYR003",
    image: "/images/TopAgent.png",
    fullname: "Rukayat Sanni",
    location: "Ilorin",
    profession: "Buyer",
    mobile: "07099887766",
    email: "rukayat.sanni@example.com",
    status: "Active",
    date: "11/12/2025",
    checked: false,
  },
  {
    id: "BYR004",
    userID: "BYR004",
    image: "/images/TopAgent.png",
    fullname: "Chidinma Nwachukwu",
    location: "Uyo",
    profession: "Buyer",
    mobile: "08122334455",
    email: "chidinma.nwachukwu@example.com",
    status: "Suspended",
    date: "12/20/2025",
    checked: false,
  },
];